version: 2.1

orbs:
  cypress: cypress-io/cypress@1.8.0

executors:
  cypress_tests:
    docker:
      - image: cypress/base:12.16.1
    environment:
      SENTRY_DSN: overwrite_value_to_disable_in_test_env
      REACT_APP_SEGMENT_WRITE_KEY: overwrite_value_to_disable_in_test_env

jobs:
  unit_tests:
    environment:
      SENTRY_DSN: overwrite_value_to_disable_in_test_env
      REACT_APP_SEGMENT_WRITE_KEY: overwrite_value_to_disable_in_test_env
    working_directory: ~/anthem
    docker:
      - image: cypress/base:12.16.1
    steps:
      - checkout

      # Restore yarn cache
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      # Install Lerna
      - run:
          name: Install Lerna
          command: npm i -g lerna

      # Install dependencies
      - run:
          name: Install Dependencies
          command: lerna bootstrap

      # Build utils/ package
      - run:
          name: Build Utils Package
          command: yarn utils:build

      # Run unit tests
      - run:
          name: Run Unit Tests
          command: yarn test

      # Persist yarn cache
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      # Persist yarn cache
      - persist_to_workspace:
          root: ~/anthem
          paths: .

  deploy_production:
    working_directory: ~/anthem
    docker:
      - image: cypress/base:12.16.1
    steps:
      - checkout

      # Restore yarn cache
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      # Build
      - run:
          name: Build the Client Application
          command: yarn client:build

      # Deploy
      - run:
          name: Deploy to Netlify
          # NOTE: Netlify has the production release branch set to the
          # branch 'fake-branch-the-real-deploy-is-in-ci' which does not exist.
          # This is because I could not find a way to publish an update to the
          # site in CI here while disabling the auto-publishing function, which
          # would deploy master without running tests. You can disable
          # auto-publishing but that incidentally "locks" the deploy, which
          # then causes this cli deploy to not publish the site. As a
          # workaround, I just changed the production release branch in Netlify
          # to a branch which does not exist. More info:
          #
          # Locked Deploys: https://www.netlify.com/docs/locked-deploys/
          # CLI Issue: https://github.com/netlify/cli/issues/536
          #
          command: ./node_modules/.bin/netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir packages/client/build --message "CI production deployed commit hash $(git rev-parse --short HEAD)"

      # Persist yarn cache
      - save_cache:
          name: Save yarn package cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

      # Persist yarn cache
      - persist_to_workspace:
          root: ~/anthem
          paths: .

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - unit_tests:
          filters:
            branches:
              only:
                - master
      - cypress/run:
          yarn: true
          working_directory: packages/cypress
          start: cd ../client && yarn dev
          # See: https://github.com/cypress-io/circleci-orb/issues/90
          wait-on: "-c packages/cypress/src/wait-on-config.json https://localhost:3000"
          executor: cypress_tests
          filters:
            branches:
              only:
                - master
      - deploy_production:
          requires:
            - unit_tests
            - cypress/run
          filters:
            branches:
              only:
                - master
