export default [
  "oasisAccountBalances",
  "oasisAccountHistory",
  "oasisTransactions",
  "oasisTransaction",
  "cosmosAccountHistory",
  "celoAccountBalances",
  "celoAccountHistory",
  "celoTransactions",
  "celoTransaction",
  "celoSystemBalances",
  "celoSystemHistory",
  "celoValidatorGroups",
  "prices",
  "fiatPriceHistory",
  "dailyPercentChange",
  "fiatCurrencies",
];
