name: Pull Request Tests

on:
  pull_request:
    branches:
      - master

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Setup NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # Run install and build steps
      # - name: Build the application and run unit tests
      #   run: yarn docker:build
      # Run Cypress e2e tests
      # - name: Run Cypress e2e tests
      #   run: yarn docker:cypress
